### ISSUE TITLE
getBarSize(new OnSizeDeterminedListener()) does not update (attachShy)

### ISSUE THREAD

**Issue by alvarlagerlof** [roughike/BottomBar#113]
This only give me one number, when my activity is first launched:

`bottomBar.getBarSize(new OnSizeDeterminedListener() {`
`    @Override`
`    public void onSizeReady(int size) {`
`        Log.e("height", String.valueOf(size));`
`        float translationY = Math.min(0, floatingActionButton.getTranslationY() - size);`
`        floatingActionButton.setTranslationY(translationY);`
`    }`
`});`

**Comment by roughike** [comment]
That one number is height on phones and width on tablets.

**Comment by alvarlagerlof** [comment]
@roughike Oh sorry, I ment that when i scroll and the bottombar hides, I need a updated number in order to reposition the fab.

**Comment by roughike** [comment]
@NikolaDespotoski , is there a way for the FAB automatically update it's position when the BottomBar hides on scroll?

**Comment by NikolaDespotoski** [comment]
@roughike I think yes. Give me some time.

**Comment by roughike** [comment]
@NikolaDespotoski 
Take as long as you want, there's no rush.

**Comment by alvarlagerlof** [comment]
Thanks @NikolaDespotoski @roughike

**Comment by NikolaDespotoski** [comment]
@alvarlagerlof @roughike I made some progress. It works fine with BottomBar but there is animation glitch when Snackbar goes down. I have to avoid/override default FAB behavior for Snackbar and apply totally new logic for handling translation of the fab for snackbar and bottombar. In the end it should work out of the box just with adding the behavior to the fab as well.

**Comment by alvarlagerlof** [comment]
It's totally fine if i need to add behavior to the tab, but can't that be done automatically?

**Comment by alvarlagerlof** [comment]
@NikolaDespotoski  I'm okay with whatever, as long as it works :smile:

**Comment by NikolaDespotoski** [comment]
@alvarlagerlof @roughike I failed. Because bottombar replaces user content view which breaks FAB behavior. For a behavior to works the target view must be direct child of coordinator layout. 

If FAB was direct child this is how my behavior works:
 ([Snackbar](https://raw.githubusercontent.com/NikolaDespotoski/BottomNavigationLayout/master/fab_behavior.gif)) 
([Scroll](https://github.com/NikolaDespotoski/BottomNavigationLayout/blob/master/fab_scroll.gif))

@roughike If you have any idea that will not break current BB implementation [here is the code for he behavior](https://github.com/NikolaDespotoski/BottomNavigationLayout/blob/master/bottomnavigationlayout/src/main/java/despotoski/nikola/github/com/bottomnavigationlayout/BottomNavigationFloatingActionButtonBehavior.java)

**Comment by alvarlagerlof** [comment]
@NikolaDespotoski Where does BottomTabLayout come from, it isn't recognized by Android studio. Sorry for late answer, is was on a lan.

**Comment by NikolaDespotoski** [comment]
@alvaragerlof It is from my library. BottomTabLayout should be BottomBar in this library, just change change the name.

**Comment by alvarlagerlof** [comment]
@NikolaDespotoski Ah, of course, thanks, trying out tomorrow

**Comment by alvarlagerlof** [comment]
@NikolaDespotoski  mNavBarSize = Util.getNavigationBarHeight(parent.getContext()); Does not find "Util", is it from the bottombar libary or somewhere else? The import list only contains "Util" from other libarys.

**Comment by Nolanus** [comment]
The method can be found in the [Util class in the linked repo](https://github.com/NikolaDespotoski/BottomNavigationLayout/blob/master/bottomnavigationlayout/src/main/java/despotoski/nikola/github/com/bottomnavigationlayout/Util.java#L117). However, the fab now is displayed outside the screen at the top and when scrolling down it moves inside the screen from above, but stays halfway behind the statusbar.

**Comment by NikolaDespotoski** [comment]
@Nolanus this is because the BottomBar tries to replace user content view within its own layout, meaning that FAB is no longer direct descendant of the CoordinatorLayout.  This is my first suspicion. 
Second is that my FAB behavior implementation I linked above is incorrectly offsetting the FAB. Because I take the bottom navigation view height as value to which FAB to be translated, and the height includes entire screen (this is because it wraps user content).

**Comment by roughike** [comment]
@NikolaDespotoski 
Actually when using ```attachShy()```, the FAB and all other Views still stay as direct child of the CoordinatorLayout, except for the View that's specified as the second argument for the method.

**Comment by NikolaDespotoski** [comment]
@roughike Then I have to adjust proper translation for FAB in the behavior.

**Comment by alvarlagerlof** [comment]
@NikolaDespotoski If you can give me a value that is updating every time the snackbar is collapsing or expanding i would be happy, please

**Comment by addiittya2006** [comment]
Is there any Update on this, the fab still goes below the BottomBar.
If I get LayoutParams and set the BottomMargin manually then the Same Margin is used as the SnackBar Margin and everything looks ugly.

**Comment by roughike** [comment]
Now since adding the BottomBar to your layout isn't so magical anymore, in the newest version you can just call ```bottombar.getHeight()```.
