### ISSUE TITLE
How to set color of bottom bar and its items?

### ISSUE THREAD

**Issue by NickM-27** [roughike/BottomBar#16]
Hello, just started checking this out and it seems really cool. However I can't seem to find out how to set the background color or item selected color? Thanks and continue the great work!

**Comment by roughike** [comment]
As of now, the colors are automatically determined according to the Material Design specification. 

When you have only three items, the active item color will be the same as your primary color. Otherwise the items are white and the background will be your primary color.

I'll add methods for customizing these in the next version.

**Comment by NickM-27** [comment]
Thanks for the reply! However it seems that this is not happening. They are always with a white background and a black icon.

**Comment by roughike** [comment]
Now you can customize the background color for each tab when there's more than five of them.

[Like this.](https://raw.githubusercontent.com/roughike/BottomBar/master/color_demo.gif)
