### ISSUE TITLE
Disable longClick event

### ISSUE THREAD

**Issue by zhywang** [roughike/BottomBar#201]
Now if you press on an inactive item, it will show a toast with the item title, what's it used for? Could we remove it?

**Comment by Nolanus** [comment]
Similar happens when long-pressing on action bar icons (http://stackoverflow.com/questions/17408365/hiding-of-the-toast-for-long-press-on-actionbar-item).
So I guess it is an accessibility "feature" (http://stackoverflow.com/questions/21278503/how-to-disable-the-long-press-event-of-action-bar-menu-item).

**Comment by shaunkawano** [comment]
I personally would like to set `OnLongClickListener` for each tab, but what do you guys think?

**Comment by yombunker** [comment]
This is a duplicate of #176
