### ISSUE TITLE
Bar is too tall with certain titles

### ISSUE THREAD

**Issue by lyptt** [roughike/BottomBar#204]
With some titles the bar seems to expand by a good 5-10dp, in my case it's the 3rd out of 5 tabs that is normal, when selecting any of the others, the bar is too large. The bar is in the sliding configuration.

Are there any ideas on a workaround for this behaviour?

**Comment by iamhadia** [comment]
I had a similar problem a few days ago. I bet the text on your 3rd tab is also the longest? Reducing the length should fix things. 

My guess is that the text has less space to occupy when the item is not selected, so it causes a line break - increasing the height of the bar by the line height. Maybe the text visibility is being set to invisible instead of gone.
