### ISSUE TITLE
OnMenuTabSelectedListener is deprecated

### ISSUE THREAD

**Issue by heartacker** [roughike/BottomBar#211]
why
![qq 20160508225013](https://cloud.githubusercontent.com/assets/1876302/15098408/a89b280e-156f-11e6-860f-e8f05f8d071d.png)

**Comment by Gallevy** [comment]
Just use OnMenuTabClickListener instead

**Comment by vbuberen** [comment]
I think it's related to Google guidlines about bottom navigation bar. As it said about behavior there: 

> Tapping on the active action in the bottom navigation bar will navigate the user to the top of the view 

So instead of `setItemsFromMenu()` with `OnMenuTabSelectedListener()`, the new `setItemsFromMenu()` use `OnMenuTabClickListener()`, which has methods `OnMenuTabSelected()` and `OnMenuTabReSelected() ` in order to allow developers implement such behavior easily.

**Comment by gkfillipus** [comment]
Hi I am also using this library, and i am having the same problem and my app crashing
i tried to use the above suggestion but no change
Any help thankx

**Comment by roughike** [comment]
[Here's how to set listeners in the newest version.](https://github.com/roughike/BottomBar#setting-up-listeners)
