### ISSUE TITLE
Framelayout overlapped by Bottombar

### ISSUE THREAD

**Issue by praveeng145** [roughike/BottomBar#243]
* Am using `compile 'com.roughike:bottom-bar:1.3.3'` and am initializing Bottombar as <br>
` final BottomBar bottomBar = BottomBar.attach(this, savedInstanceState);` <br>
from my Activity's onCreate()
* Am attaching another FrameLayout via ActivityLifeCycleCallback.onActivityResumed(). Am adding this FrameLayout as a child to <br> `((ViewGroup) activity.findViewById(android.R.id.content))`.
* By the time I attached my custom FrameLayout, <br>`((ViewGroup) activity.findViewById(android.R.id.content))` <br>

already has Bottombar at index 0, and my FrameLayout is attaching at index 1.
* So the expected behavior is my FrameLayout should appear as an overlay on top of Bottombar, which is not the case in this particular scenario. 
* My FrameLayout is hidden by Bottombar.
* To my surprise, when debugged via Android's HierarchyViewer shows my FrameLayout as the top layout and Bottombar as the next one. In actual device or emulator it is otherwise.
* Pls take a look at the screenshot of the same. <br> <img width="284" alt="screen shot 2016-05-22 at 1 48 31 pm" src="https://cloud.githubusercontent.com/assets/2502003/15456431/8eca1682-2024-11e6-8d4a-b0bf7951e1ae.png">

**Comment by Nolanus** [comment]
As the bottombar is attaching itself as a new view to the android content's view it's not surprising that it interferes with self-attached views.
As `onActivityResumed()` might be called multiple times during an activities lifecycle it's likely not the best place for attaching that view.
Another question I've got is, what you want to achieve with attaching the framelayout manually. If you only want to put a "loading overlay" atop the view maybe you can show a dialog instead of putting new views to the Viewgroup (like [ProgressDialog](https://developer.android.com/reference/android/app/ProgressDialog.html))?

**Comment by praveeng145** [comment]
@Nolanus thanks for your comments. The approach which I implemented via `onActivityResumed()` is working great across different apps. So far no issues observed. Coming to what am trying to achieve is to mimic FAB kind of button, which is movable and actionable. So I had chosen `FrameLayout` and adding this layout atop of all the views. Is there any workaround that I can force the `BottomBar` to stay behind my view ?

**Comment by roughike** [comment]
This shouldn't be a problem with the newer versions (2.0 and up) of this library. The BottomBar is now just a regular View you can add to your XML layout.
