### ISSUE TITLE
Translate animation make the whole screen move

### ISSUE THREAD

**Issue by renaud-myatlas** [roughike/BottomBar#282]
Hello,

I would like to do something like that with my BottomBar (see following code) but it make the whole layout move with my bottomBar.
Am I doing it the wrong way ?

```
        Animation animation = AnimationUtils.loadAnimation(this, R.anim.move);
        mBottomBar.startAnimation(animation);
```
with anim/move.xml
```
<?xml version="1.0" encoding="utf-8"?>
<set
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:interpolator="@android:anim/linear_interpolator"
    android:fillAfter="true">
    <translate
        android:fromXDelta="0%p"
        android:toXDelta="100%p"
        android:duration="500" />
</set>
```

Thank you very much

**Comment by JonathanMerritt** [comment]
Try 
`mBottomBar.getBar().startAnimation(animation);
`

mBottomBar includes the content frame.

**Comment by renaud-myatlas** [comment]
Thanks but it doestn't work. Now only the content of the bar is animated and I want the whole bar to be animated.

**Comment by JonathanMerritt** [comment]
You may have to include the library in your project and adjust some things.

I'm assuming there are methods in it that are used for shyHiding/Showing, that are private or something. 


You also could hack up something, like maybe fool the bottom bar into thinking your hide action is a scroll event from its attached scroll view. Instead of creating your own animation. That's just off the top theory though.

**Comment by renaud-myatlas** [comment]
I guess I'll deep in the source code then :)
Thanks for your advice @JonathanMerritt

**Comment by roughike** [comment]
Now the BottomBar is just like any regular View, and you can move it without moving the whole screen.

**Comment by renaud-myatlas** [comment]
Thanks for your work @roughike !!!
