### ISSUE TITLE
Is it possible to set the color of the icons in the bottom bar?

### ISSUE THREAD

**Issue by elliottdehn** [roughike/BottomBar#293]
I'm currently developing an app for internal use purposes and am currently trying to make it so that the icons in the bottom bar are a darker color. They're currently white. Is there any way to change this?

**Comment by sarang1996** [comment]
i also want to change color of icon and textview, currently those are white but i want it grey.

**Comment by akshayspeaks** [comment]
@roughike I'm facing the same issue.

@elliottdehn @sarang1996 If I'm not wrong, you are using drawables while creating new BottomBarTab instead of resource id. What I've noticed, is that if you pass even 1 BottomBarTab that is set using resource id along with the others, you will get a colored bottom bar nav.

Kindly look into it.

**Comment by Adefunke** [comment]
@roughike, I am also having this issue.
To be specific, mine is that; the bottomBar is colorAccent and when I click on tabs it does not show me a change in color.
I used R.menu,bottomtab to declare the items.

**Comment by roughike** [comment]
[See the README](https://github.com/roughike/BottomBar#all-customization-options)
