### ISSUE TITLE
Using attach(Activity activity, Bundle savedInstanceState, int backgroundColor, int activeIconColor, float alpha) causes NullPointerException

### ISSUE THREAD

**Issue by CarlosUrbina** [roughike/BottomBar#374]
Trying to attach the BottomBar using the method attach(Activity activity, Bundle savedInstanceState, int backgroundColor, int activeIconColor, float alpha) causes the variable `mInActiveColor` never to be set, causing the followig error:

``` Java
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
    at com.roughike.bottombar.BottomBar.unselectTab(BottomBar.java:1555)
    at com.roughike.bottombar.BottomBar.updateItems(BottomBar.java:1358)
    at com.roughike.bottombar.BottomBar.setItems(BottomBar.java:343)
```

Using com.roughike:bottom-bar:1.4.0.1, whit the following code:

``` Java
bottomBar = BottomBar.attach(this,savedInstanceState,ContextCompat.getColor(this,R.color.menu_light_blue_1),
                ContextCompat.getColor(this,R.color.menu_light_blue_3),128f);
        bottomBar.setItems(R.menu.peq_bottombar);
```

**Comment by smallzhan** [comment]
Same error  here with 1.4.0 and 1.4.0.1

**Comment by aolsenjazz** [comment]
@CarlosUrbina @smallzhan Calling `BottomBar.setFixedInactiveIconColor(int color);` after `BottomBar.attach(...)` will fix this. I assume this is throwing an NPE because `mInActiveColor` isn't being set in `bar.init()` due to `mWhiteColor` being non null. There are a couple commented out blocks that follow it which may have remedied this.

**Comment by roughike** [comment]
Fixed in the newest version.
