### ISSUE TITLE
bar is on top my layout

### ISSUE THREAD

**Issue by avivcaspi** [roughike/BottomBar#449]
the problem is that the bar is floating above the layout, so the space where the bar is blocked,
even with scrollview it is not possible to get reach it.
is there a way to make the bar not float
?

**Comment by roughike** [comment]
Can you provide me some details how you're using the BottomBar in your layout?

**Comment by mariizcal** [comment]
I had the same problem. But in my case it was a easy to solve it. Because now the BottomBar is a **widget** in the xml layout, that means that you have to specify a position in the layout. For example this is my **layout**

```
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <FrameLayout
        android:id="@+id/fragment_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginBottom="60dp"/>

    <com.roughike.bottombar.BottomBar
        android:id="@+id/bottomBar"
        android:layout_width="match_parent"
        android:layout_height="60dp"
        android:layout_gravity="bottom"
        app:bb_tabXmlResource="@xml/bottombar_tabs" />
</FrameLayout>
```

I was using a FrameLayout as a Parten container and one of the rules of a FrameLayout is that all the View in the container will overlap, so in my case i just gave a marginBottom to **"@+id/fragment_container"**  of *60dp* (The size of the BottomBar).

Hope it helps!

**Comment by avivcaspi** [comment]
yes thank you very much!
