### ISSUE TITLE
Incorrect behavior with painted element above bottombar

### ISSUE THREAD

**Issue by Zey-Uzh** [roughike/BottomBar#463]
Bottombar 2.0.2, android API 23

I just added android:background="#7283e1" to TextView in the example.  

If i have enabled shadow (by default), then the white stripe appears between bottombar and the element above it. 
If i disable a shadow, then everything is fine.     

![bottombar_incorret_behavior](https://cloud.githubusercontent.com/assets/9356399/18091082/7d2639e4-6ed8-11e6-9c85-b2c96693333a.png)

**Comment by FizzyMobile** [comment]
Shadow's height (which is currently 4dp) is considered during layout. So that for layout:
```
 <com.roughike.bottombar.BottomBar
                android:id="@+id/bottom_bar"
                android:layout_width="match_parent"
                android:layout_height="56dp"
                android:layout_alignParentBottom="true"/>

 <FrameLayout
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_above="@id/bottom_bar"/>
```
your content is placed above the shadow as well (the white space is just containter's background color).

If your bottom bar has defined height then instead of setting 
`android:layout_above"` use `android:layout_marginBottom` (bottom bar height - 4dp).

**Comment by roughike** [comment]
Fixed in 2.3.0.

**Comment by yombunker** [comment]
@Zey-Uzh @FizzyMobile the latest version is out, has some fixes for shadows

**Comment by Zey-Uzh** [comment]
Cool! Thx!
