### ISSUE TITLE
Bottom navigation items keep the primary color after de-selecting in some cases

### ISSUE THREAD

**Issue by Discover-** [roughike/BottomBar#470]
This is how I load the drawables per bottom navigation item:

``` java
Drawable drawable = null;

try {
    drawable = ResourcesCompat.getDrawable(getResources(),
            getResources().getIdentifier(menuItemInfo.ModuleDrawableName, "drawable", getPackageName()), null);
}
catch (Exception e) {
    e.printStackTrace();

    try {
        drawable = ResourcesCompat.getDrawable(getResources(), R.drawable.ic_warning_black_24dp, null);
    }
    catch (Exception e2) {
        e2.printStackTrace();
    }
}
```

This is how it looks (and should look) when I start the app: http://i.imgur.com/rVm1Quj.jpg
This is how it looks after I selected each bottom item from left to right: http://i.imgur.com/d8bupwC.jpg

**Comment by roughike** [comment]
What version of the library are you using? What does your tab xml file look like?

**Comment by Discover-** [comment]
I'm still using 1.3.3 because I have to generate the bottom navigation items dynamically instead of through resources. This means I also don't have a tab xml file, because this wasn't introduced back with my version.

**Comment by roughike** [comment]
I see! I remember having that problem with the v1 as well.

The thing is, the "first generation" of BottomBar was (in my opinion) some horrible spaghetti code. It kinda worked, but was a real PITA to maintain, because the code was so messy. On top of that, it had no tests and that's why some bugs were reintroduced after fixing other ones. Including that one you just described, which was (if I remember correctly) already fixed before.

I'm adding the support to inflate items dynamically to the new version when I can though, as it's been requested many times.

**Comment by Discover-** [comment]
Ah I see. I wish I had time to make a pull request with the implementation, but I'm not in that position right now. Thanks for not closing it directly and ignoring the issue because it's not the latest release!

**Comment by roughike** [comment]
Your version of the "first generation" BottomBar is still outdated.

[See if the "newest old" version fixed this issue.](https://github.com/roughike/BottomBar/tree/v1)

**Comment by Discover-** [comment]
I've tried 1.4.0.1 but it actually brought a new issue where the icons and text are overlapping each other. They both seem to be put in the vertical center position now.

**Comment by roughike** [comment]
I've decided that v1 will be discontinued, so I'm closing this one. Please switch to the latest versions.
