### ISSUE TITLE
Set Shadow Height?

### ISSUE THREAD

**Issue by josefkorbel** [roughike/BottomBar#489]
Hi, i cant figure out how to change the ImageView's (Shadow) height, can anyone please help me out?

**Comment by kikoololmdrxdd** [comment]
private BottomBar bottomBar;

protected void onCreate(Bundle savedInstanceState) {
          bottomBar = (BottomBar) findViewById(R.id.bottomBar);
          bottomBar.findViewById(R.id.bb_bottom_bar_shadow).getLayoutParams().height= 4; // set height to 4dp.
}

**Comment by yombunker** [comment]
@kikoololmdrxdd that would actually be 4Px not 4Dps, but, this is not something we are intending to change because this is only a "hack" for 4.4, if you are using API 21+ or above then you can just change the elevation of the BottomBar and it will override our default elevation. (Anyways there's a small fix for the shadow that will be going out in next release)

**Comment by yombunker** [comment]
@kikoololmdrxdd @josefkorbel  the latest version is out, has some fixes for shadows
