### ISSUE TITLE
How to refresh bottombar in java code when i already set it in xml

### ISSUE THREAD

**Issue by chenshaoyebj** [roughike/BottomBar#554]
Now the problem is when i already set tab item in the activity xml with "bb_tabXmlResource "parameter after then I want refresh the items in the java code , When I use  "setItems( )"method the bottombar just not work as normal , anyone meet same problem???

**Comment by bresan** [comment]
Hello @chenshaoyebj :-) I run through this issue, and the best way I've found was just to add the bottom bar dynamically through code, like 

```java
BottomBar bottomBar = new BottomBar(this);
bottomBar.setItems(R.xml.items);
```

and then later add it into layout programatically, like this:


```java
LinearLayout linearLayout = (LinearLayout) findViewById(R.id.your_layout);
LinearLayout.LayoutParams layoutParams =
                (RelativeLayout.LayoutParams) bottomBar.getLayoutParams();
layoutParams.addRule(LinearLayout.BOTTOM, 1);
bottomBar.setLayoutParams(layoutParams);
linearLayout.addView(bottomBar);
```
Hope it can help you, it was the way I've done it, since adding it programatically (setItems) after setting on XML, resulted in really strange behavior (adding like two times and the clicks on the view were buggy).

Any questions feel free to ask :-)

**Comment by RiteshChandnani** [comment]
@chenshaoyebj 
Even I am facing same problem.
Any other way of doing this because that code is not working.
Casting is wrong.

`LinearLayout.LayoutParams layoutParams =
                (RelativeLayout.LayoutParams) bottomBar.getLayoutParams();`

So, after casting it to LinearLayout setting gravity isn't working.
And I think we can't set the app:bb_behaviour programmatically.
Not working for me :(

**Comment by amenon** [comment]
I've fixed this issue of being able to add items programmatically in my pull request from Sep 23rd https://github.com/roughike/BottomBar/pull/512, but this hasn't been merged as yet

**Comment by RiteshChandnani** [comment]
@amenon 
Thanks!  :) 
Hopefully it will be merged soon.

**Comment by roughike** [comment]
Merged and thus fixed. Thanks @amenon !
