### ISSUE TITLE
How reload a fragment?

### ISSUE THREAD

**Issue by Haoxiqiang** [roughike/BottomBar#75]
Sometime,I have to reload a tab.How to do  it ?

**Comment by roughike** [comment]
Are you using the setFragmentItems() method?

**Comment by Haoxiqiang** [comment]
I want just update or reload only one fragment.I don't know what is the best way.For example,there are  five fragments,each one will get the data from the network,now all fragments load finished.If do login,the first fragment should refetch data.BottomBar does't support get the current fragments.should I handle all the fragments instance?

**Comment by roughike** [comment]
This issue is not related to the library.

Even with the ```setFragmentItems()``` method you can just first assign your Fragments to variables and pass the variables instead of Fragments as arguments. But should handle the Fragments by yourself, as the ```setFragmentItems()``` method is deprecated.

Read up on communicating between Fragments and Activities.
