### ISSUE TITLE
 Snackbars don't go above the bottom bar with attachShy() 

### ISSUE THREAD

**Issue by polyvjk** [roughike/BottomBar#89]
I give my snackbar the root CoordinatorLayout and it was showing above the bottom bar when using just attach(this, ...) (as described in the issue  ["Snackbars should go above the bottom bar. #36" ](https://github.com/roughike/BottomBar/issues/36)) but when I now use attachShy() it overlaps the bottom bar.

**Comment by chemickypes** [comment]
I'm in same situation.

I had problem using `BottomBar.attach(this,...)` using CoordinatorLayout (the view doesn't match the parent) so I user `BottomBar.attachShy(...)` and view was ok, but snackbar overlaps bottom bar yet.

**Comment by chemickypes** [comment]
@roughike I got a strage case related this problem.

I'm studying your library and I see this [tutorial](http://androidgifts.com/build-android-material-design-bottom-navigation/): with 3 elements all is ok bottom bar is grey and snackbar doesn't overlap bar, but when I add 2 elements I get a lot of space above toolbar (like this [issue](https://github.com/roughike/BottomBar/issues/61)), bottom bar becomes blue and snackbar overlaps it.

**Comment by NikolaDespotoski** [comment]
@roughike This is due to CoordinatorLayout adding the snackbar at z order that makes your BottomBar have lower z index than the snackbar view. I had this issue in my lib. Take a look how I solved it [here](https://github.com/NikolaDespotoski/BottomNavigationLayout/blob/master/bottomnavigationlayout/src/main/java/despotoski/nikola/github/com/bottomnavigationlayout/BottomNavigationBehavior.java).  PreLollipopBottomNavWithSnackBarImpl inner class. Basically, calling child.bringToFront() allowed me to ask CoordinatorLayout to grant my layout same z order as before just at same moment the snackbar is added to the CL.

**Comment by NikolaDespotoski** [comment]
@roughike I didnt have issues on APIs that support elevation because the bottom bar should be always above snackbar as said in specs. On older apis I had to reorder the layout to front so Snackbar now is below my layout.

**Comment by NikolaDespotoski** [comment]
@chemickypes Fixed in PR #111. @roughike please review it

**Comment by NikolaDespotoski** [comment]
@roughike This is basically, what I said in the comment. The code is copied from my library and works flawlessly with yours. :)
