### ISSUE TITLE
Launch Activity on tab selection in bottombar

### ISSUE THREAD

**Issue by alfox10** [roughike/BottomBar#91]
Hi!
I saw your example, but I want to launch an Activity instead of a layout.
Can you help me to undestand how can I do that?

Thanks

**Comment by ncapdevi** [comment]
````
bottomBar.setItemsFromMenu(R.menu.your_menu, new OnMenuTabClickListener() {

 @Override
 public void onMenuTabSelected(@IdRes int menuItemId) {
   switch(menuItemId){
    case R.id.YOU_ITEM1:
    //LAUNCH ACTIVITY 1
    break;
    case R.id.YOU_ITEM2:
    //LAUNCH ACTIVITY 2
    break;
    case R.id.YOU_ITEM3:
    //LAUNCH ACTIVITY 3
    break;
   }
 }
 @Override
 public void onMenuTabReSelected(@IdRes int menuItemId) {
  //HANDLES A TAB BEING RESELECTED
 }
})
```

**Comment by alfox10** [comment]
Hi thanks for your reply, I already did this. And reading again my post I forgot to specify that I want the activity inside the fragment, with this method the activity is launched "full screen" and I can't see anymore the bottom bar

**Comment by ncapdevi** [comment]
@alfox10 That's not really the design case for activities.  An activity is, by it's nature, a full screen view.  It seems like the functionality that you're really looking for is to use a fragment within a main activity that uses a tab bar, which is what I highly recommend.  If you were to do it your way, you would need to create a new tab bar for Activity B, and set it to the same properties, and then set it to it's current state.  Since the tab bar is only meant to be used with between 3-5 items (per the spec sheet), you would need to do this for 3-5 activities. I highly do not recommend doing things this way. It doesn't follow the Android design pattern, nor is it efficient or manageable.

**Comment by alfox10** [comment]
oh thanks a lot, I understand my mistake. I'm going to use Fragment

Thanks again

**Comment by ncapdevi** [comment]
Not a problem. Just FYI, unfortunately, managing multiple deep stacks (a stack of fragments per tab that go more than 2 fragments deep) can be a bit of a task.  There's not a simple method to handle this within the framework, so you'll have to write up your own management class. That being said, I may post a library for handling this stuff in the next week or so, since it's such a hassle.  Best of luck.
